### PR TITLE
Add ES 6.2.1 support based on ES 6.2.2

### PR DESCRIPTION
**Pull request by 9072997**
Merged in changes from master, then just did a `sed -i 's/6.2.2/6.2.1/g' build.gradle`. Strangely I had to unzip and re-zip the file before elasticsearch would install it. it was failing with:
> ERROR: `elasticsearch` directory is missing in the plugin zip

I'm assuming that was an issue with my build environment. Once I re-ziped it though, everything seemed to work fine.
It would help us out if this made it to http://es-learn-to-rank.labs.o19s.com/ quickly
#132

### CODE REVIEW

**Comment by nomoa** [comment]
The build pass for me and the zip file is correct.
@purbon would you mind taking a look if you still have time to take care of the releases on this plugin?

**Comment by purbon** [comment]
@nomoa yes, I can do that, I will take a look during the weekend!

**Comment by purbon** [comment]
Hi @nomoa  and @9072997  I cherry picked your commit into the 6.2.1 branch (you can see https://github.com/o19s/elasticsearch-learning-to-rank/commit/7ba2d0eb27c968157dc6d8104981cda4a12d2807 ) and I will push a new version right now. Thanks a lot for your contribution and again, sorry for the delay on taking care of this PR.

**Comment by purbon** [comment]
the artifact is available to download from http://es-learn-to-rank.labs.o19s.com/ltr-1.0.1-es6.2.1.zip

**Pull request closed without merging**
