### PR TITLE
Version bump for es 7.17.5

### PR DESCRIPTION
**Pull request by mifune-cedrowo**
Executed clean check as per CONTRIBUTING.md:

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :compileJavaRestTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 14s
23 actionable tasks: 20 executed, 3 up-to-date

### CODE REVIEW

**Comment by nathancday** [comment]
This is awesome, thanks! ❤️

**Comment by mifune-cedrowo** [comment]
@nathancday do you know when we can expect this version bump to be merged and package published?
Thanks!

**Comment by nathancday** [comment]
how about right now? (thought it was, thanks for the nudge)

**Comment by mifune-cedrowo** [comment]
@nathancday thank you!

**Pull request merged**
