### PR TITLE
ES 7.16.1

### PR DESCRIPTION
**Pull request by DAVIDFlavien**
We run ES 7.16.1 and use LTR, we would like to rely on Github's action to tag and publish a release.

### CODE REVIEW

**Comment by DAVIDFlavien** [comment]
I just figured out that version `7.16.1` has not yet been published on https://mvnrepository.com/artifact/org.elasticsearch.gradle/build-tools.

**Comment by nathancday** [comment]
Never bad to be ahead of ES, thanks for kicking this upgrade off

**Comment by worleydl** [comment]
I just updated things for 7.16.0.  You'll need to rebase on those changes but hopefully when the build tools are available it's as simple as your current commit for 7.16.1 🤞

**Comment by DAVIDFlavien** [comment]
Following https://github.com/elastic/elasticsearch/releases/tag/v7.16.1, this PR is now good to go.

**Comment by worleydl** [comment]
Merged and release on the way. Thanks.

**Pull request merged**
