### PR TITLE
Update elasticsearch to 8.7.0 and lucene to 9.5.0

### PR DESCRIPTION
**Pull request by Philippus**
According to the release notes of elasticsearch 8.7.0 lucene got an upgrade in it: https://www.elastic.co/guide/en/elasticsearch/reference/8.7/release-notes-8.7.0.html.

### CODE REVIEW

**Comment by cdmbr** [comment]
@Philippus should we bump to 8.7.1 since there is a new es release ?

**Comment by nathancday** [comment]
Didn’t realize this was still open. Will get this merged and a version bump
out today. Huge thanks to @Phillippus, you da MVP.

**Comment by Philippus** [comment]
Probably good to have releases for both 8.7.0 and 8.7.1.

**Comment by nathancday** [comment]
gotta love ES renaming classes, thanks again for the PR!

**Pull request merged**
