### PR TITLE
Fix irreproducible inference due to the imprecise floating point values in xgboost's get_dump

### PR DESCRIPTION
**Pull request by pltb**
Tries to address the issues of using the output of the `get_dump` method in xgboost as the import format by parsing the output of `save_model` instead

More context here https://github.com/o19s/elasticsearch-learning-to-rank/issues/497

TODO:
- [x] parse using ObjectParser
- [x] add more tests
- [x] review from the plugin's authors

### CODE REVIEW

**Comment by pltb** [comment]
TODO:
- parse using ObjectParser
- add more tests

**Comment by wrigleyDan** [comment]
Summary of our chat at Haystack:

* Rename the parser to `model/xgboost+json+v2`
* Add the switch-case for the additional model parser
* Preserve existing functionality
* Add tests

**Comment by pltb** [comment]
@wrigleyDan a small correction: shall we rename it to `model/xgboost+json+raw` instead of v2?

**Comment by wrigleyDan** [comment]
> @wrigleyDan a small correction: shall we rename it to `model/xgboost+json+raw` instead of v2?

Thanks, copied the old name and forgot to change it. Well spotted, corrected it in the comment above.

**Comment by pltb** [comment]
Hi @wrigleyDan, I've pushed a few changes that should cover most of the action points that we've outlined:

- added 8 tests for some basic parsing cases (I'd love to see more extensive testing here, but I'm not sure if this should be a blocker for merging this version of the parser)
- added some extra validation and refactored the code a little bit
- renamed the parser like we've agreed
- registered the parser in the plugin

Please let me know I can provide any assistance with the docs and the notebook, I'd be glad to help :D

**Comment by wrigleyDan** [comment]
Thanks for making the changes so quickly!
There are a couple of tasks failing when executing the tests around checkStyle:

```
> Task :checkstyleTest
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:56: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:115: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:173: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:227: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:282: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:336: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:397: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:458: Line is longer than 140 characters (found 152). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/test/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParserTests.java:511: Line is longer than 140 characters (found 152). [LineLength]

> Task :checkstyleTest FAILED

> Task :checkstyleMain
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:8:34: Using the '.*' form of import should be avoided - org.elasticsearch.xcontent.*. [AvoidStarImport]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:12:17: Using the '.*' form of import should be avoided - java.util.*. [AvoidStarImport]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:42: Line is longer than 140 characters (found 156). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:66: Line is longer than 140 characters (found 149). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:120: Line is longer than 140 characters (found 159). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:121: Line is longer than 140 characters (found 178). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:170: Line is longer than 140 characters (found 155). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:177:9: Redundant 'public' modifier. [RedundantModifier]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:197: Line is longer than 140 characters (found 149). [LineLength]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:217:9: Redundant 'public' modifier. [RedundantModifier]
[ant:checkstyle] [ERROR] /path/to/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/ranker/parser/XGBoostRawJsonParser.java:248:9: Redundant 'public' modifier. [RedundantModifier]

> Task :checkstyleMain FAILED
```

Could you have a look and resolve these so we don't see any checkStyle violations when running the tests?

Thanks!

**Comment by pltb** [comment]
@wrigleyDan ah I totally missed it 😅 
Fixed, thanks!

**Pull request merged**
